repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: Run npm lint
        entry: bash -c "cd ayudar && npm run lint"
        language: system
        pass_filenames: false
        stages: [pre-commit]